### ISSUE TITLE
suggestion/question

### ISSUE THREAD

**Issue by beroe** [mongiardino/deWoRMR#1]
The end product certainly is useful, but ... wouldn't you be able to achieve the same result **much** more quickly using their REST API instead of loading all the extraneous info from the web pages? You could pull 50 children at a time and keep pulling children and parsing JSON until you run out? 

https://www.marinespecies.org/rest/AphiaChildrenByAphiaID/1258?marine_only=true&offset=1

**Comment by mongiardino** [comment]
Hi Steven,

100% absolutely yes. Probably using functions from their 'worrms' package would make this a ton more efficient while not requiring massive changes to the code, and I will do that when I get the time. The script was written ~ 5 years ago, before those tools existed. I still think this works ok, and people can benefit from it while I make it more efficient.

I would also note that while being strictly speaking **very** inefficient, as the same can be achieved in orders of magnitude less time, I only update my taxonomic database once a year (and many times see no changes). Having it running in the background for about an hour every 1 or 2 years, while slow, is not really the limiting factor in anything that I do. I think that under the alternative definition of efficiency that accounts for which is the limiting factor of a process, this is still highly efficient. Things do get different for those interested in getting data for a much larger clade.

Cheers!
Nico

**Comment by beroe** [comment]
Hi Nico. Thanks for the reply. Totally agree. I have a ton of scripts where I got it working, I occasionally use it, and that makes it not worth the time of optimizing. Somewhat the XKCD situation...
![image](https://github.com/mongiardino/deWoRMR/assets/871533/48c41e87-2d9c-4b7d-a5c4-0ac65694a980)
I wish I had a chunk of free time to contribute because I can see myself using this project...

**Comment by beroe** [comment]
No need to keep this as an active issue ;^)
